image: node:latest

cache:
    paths:
    - node_modules/

before_script:
    - npm i -g yarn
    - yarn

pages:
    script:
    - yarn build
    - yarn test
    - yarn deploy
    artifacts:
        paths:
        - public
