image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm i

build:
  stage: build
  script:
    - npm run build

report:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  only:
    - master
  script:
    - npm run report
    - npm run deploy
  artifacts:
    paths:
      - public
